### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by Stinkfist0** [realXtend/tundra-urho3d#14]
FYI, running into errors during OpenSSL build when trying VS 2015 build (both x86 & x64)
```
        link /nologo /subsystem:console /opt:ref /debug /out:out32\constant_time_test.exe @C:\Users\Ali\AppData\Local\Temp\nm7651.tmp
constant_time_test.obj : error LNK2019: unresolved external symbol __iob_func referenced in function main
out32\constant_time_test.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
Stop.

Microsoft (R) Program Maintenance Utility Version 14.00.23026.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Building OpenSSL
        link /nologo /subsystem:console /opt:ref /debug /out:out32\constant_time_test.exe @C:\Users\Ali\AppData\Local\Temp\nm77C6.tmp
constant_time_test.obj : error LNK2019: unresolved external symbol __iob_func referenced in function main
out32\constant_time_test.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
Stop.
```
For Perl I am using strawberry-perl-5.20.3.1-64bit-portable.zip

**Comment by jonnenauha** [comment]
Might be something that is fixed in the latest 1.0.1 release https://github.com/openssl/openssl/releases/tag/OpenSSL_1_0_1p 

You can just change the tag checkout in the build script to `OpenSSL_1_0_1p` here https://github.com/realXtend/tundra-urho3d/blob/master/tools/Windows/BuildDeps.cmd#L297

Might be a good idea at the same time to update curl (why we build openssl in the first place) to https://github.com/bagder/curl/releases/tag/curl-7_45_0 again branch to `curl-7_45_0` here https://github.com/realXtend/tundra-urho3d/blob/master/tools/Windows/BuildDeps.cmd#L355

**Comment by cadaver** [comment]
If that error comes just from building a test executable, sounds like it could be skipped?

**Comment by Stinkfist0** [comment]
I'll try updating OpenSSL and Curl first. But yeah, completely insignificant test biz could be skipped, if possible.

**Comment by Stinkfist0** [comment]
Updating OpenSSL to 1.0.2d fixed the build. Updating Curl caused the build to fail with VS 2015, but the current Curl version builds OK.

**Comment by jonnenauha** [comment]
I think OpenSSL keeps two version tracks 1.0.1 and 1.0.2, afaik it has been like this for years. I would suspect 1.0.2 has some API changes that certain projects might not work with. Did you try the latest 1.0.1 + latest Curl? Maybe they used something that no longer worked with 1.0.2? Dunno...

In general should always try to use latest OpenSSL when they arrive. So should be fine to update for all VC. Linux uses PolarSSL https://github.com/realXtend/tundra-urho3d/blob/master/tools/Linux/Ubuntu/Build.bash#L263-L265 that Curl also supports. Somehow it was just less hassle. We should update that one too to latest (and curl) if someone has time.

**Comment by jonnenauha** [comment]
Using latest ssl libraries is always the right call, but more critical for projects that do HTTPS hosting. Usually security bugs are on the server side, we are using OpenSSL purely to support Curl HTTPS GET for resources at the moment. Ofc client chiphers and other stuff can get updated so it's important to be up to date.

**Comment by Stinkfist0** [comment]
@jonnenauha Yes, latest OpenSSL 1.0.1p failed to build. Quick googling would suggest that this error occurs when doing static lib build, but not when doing dynamic lib build. Buliding latest Curl failed with OpenSSL 1.0.2d.

**Comment by cadaver** [comment]
Websocketpp says they support TLS. Naturally the devil is in the details once we actually try running it.

**Comment by Stinkfist0** [comment]
Should I commit the VS 2015 with OpenSSL update to 1.0.2d or should we leave this pending for now?

**Comment by jonnenauha** [comment]
I think you can commit if it also works on older VS. If you could try 2010 works. Leave the curl as is then.

It took a fair bit of time to get curl linked with static OpenSSL, similar is done in linux with PolarSSL. I did this to avoid the /bin DLL hell of Tundra. Hopefully we don't need to go to dynamic linking due to this.

**Comment by Stinkfist0** [comment]
I'll test with 2013.

**Comment by Stinkfist0** [comment]
BTW didn't find an obvious way for disabling building tests for OpenSSL. I'll test HTTPS biz by using TXML from Dropbox and if it works, I'll commit the OpenSSL update and VS 2015 support.

**Comment by Stinkfist0** [comment]
Lasse was getting the same error for VS 2013 + OpenSSL 1.0.1 build so I decided to pull the trigger on this.

**Comment by cadaver** [comment]
VS2010, 2013 and 2015 deps all seem to be building fine. Had to update CMake though, curl couldn't build with CMake 3.1.0.
