### ISSUE TITLE
Log file doesn't have native line endings on Windows

### ISSUE THREAD

**Issue by Stinkfist0** [realXtend/tundra-urho3d#15]
Running Tundra.exe and shutting down and inspecting the Tundra.log file by double-clicking it (opens up in Notepad):

E: GitHub automatically converts the line endings, so you'll have to check them out yourselves :)

**Comment by cadaver** [comment]
On a VS2013 build, I am seeing 0x0d 0x0a for each line, which is also the behavior for Urho3D itself. If you're interested, look at PrintUnicode in Urho's ProcessUtils.cpp

The log file is opened as a binary file initially, though, as Urho doesn't even have the concept of text open mode.

**Comment by Stinkfist0** [comment]
Yeah, the Urho's internal prints are ok, but Tundra's print not for some reason.
